### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by zhujinwen0924** [nabeelsherazi/rtplot#5]
python timeseries_example.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 118, in _on_timer
    TimerBase._on_timer(self)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/animation.py", line 1447, in _step
    still_going = Animation._step(self, *args)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/animation.py", line 1173, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/animation.py", line 1192, in _draw_next_frame
    self._draw_frame(framedata)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/matplotlib/animation.py", line 1755, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/rtplot/core/internal.py", line 135, in plot_update_master
    updated = self.plot_update(frame_number)
  File "/home/leoh/anaconda3/envs/Robotics/lib/python3.8/site-packages/rtplot/core/internal.py", line 263, in plot_update
    frac_outside = outside_bounds_mask[:, i].sum() / outside_bounds_mask[:, i].size
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by nabeelsherazi** [comment]
Hi! a thanks for creating this issue! Admittedly, I remember this bug occurring, but haven’t used or developed this library in some time. If you have interest in working on this issue, I could give you pointers on what needs to be fixed!
